--INCLUDE_CONKY "./conky_header.conf"
    alignment = 'top_right',
    gap_y = 20,
    gap_x = 1940,
    own_window_transparent = no,
    own_window_argb_visual = true,
    own_window_argb_value = 80,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_class = 'Conky',
}

conky.text = [[
${color grey}Qubes VM performance:
${execp ./util/no_dm | sed -r -n 's/^\s*([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+.*$/\1${goto 270}\4${goto 350}\9${goto 420}\5${goto 500}\6${goto 550}/p'}
$hr
${color grey}Qubes global preferences:
NAME${goto 370}VALUE
${execp qubes-prefs | sed -r -n 's/^([^ ]+)[ ]+([^ ]+)[ ]+([^ ]+)/\1\${goto 370}\3/p'}
$hr
${color grey}Last qrexec requests:

#${execp bash -c 'x="$(journalctl -b0 -u qubes-qrexec-policy-daemon -g "qrexec:" --no-pager -n10 --quiet | sed -rn "s/dom0.*qrexec: //p")" ; echo -n "${x::90}"'}
${execp journalctl -b0 -u qubes-qrexec-policy-daemon -g 'qrexec:' --no-pager -n10 --quiet | sed -rn 's/dom0.*qrexec: //p' | cut -c 1-90}
--INCLUDE_CONKY "/etc/conky/conky_qubesSettings_custom.conf"
]]
