--INCLUDE_CONKY "./conky_header.conf"
    alignment = 'top_left',
    gap_y = 490,
    gap_x = -1900,
    own_window_transparent = no,
    own_window_argb_visual = true,
    own_window_argb_value = 80,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_class = 'Conky',
}
conky.text = [[${font NotoSansMonoCJKSC:size=8}${execp ./util/qvm-ls-conky}${font}]]
